services:
  - type: web
    plan: free
    name: Bucket-Rename-Bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    repo: https://github.com/axomlegendyt/Bucket-Rename-Bot.git      
    branch: main
    envVars:
      - key: API_ID 
        sync: false
      - key: API_HASH 
        sync: false
      - key: TOKEN
        sync: false
      - key: ADMIN
        sync: false
      - key: DB_URL
        sync: false
      - key: DB_NAME
        sync: false 
      - key: CHANNEL
        sync: false
      - key: LOG_CHANNEL
        sync: false    
    autoDeploy: false
